name: only_pets
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+4
  curved_navigation_bar: ^1.0.3
  lottie: ^2.7.0
  flutter_launcher_icons: ^0.13.1
  window_manager: ^0.3.8
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/logo.png"
  adaptive_icon_background: "#ffffff"    # or a path to an image
  adaptive_icon_foreground: "assets/img/logo.png"